spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elgrandeproject
    username: postgres
    password: nikola
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.highlight_sql: true
server:
  error:
    include-message: always
    include-binding-errors: always
