################## ROLE

POST localhost:8080/api/v1/admin/roles
Content-Type: application/json

{
  "name": "ADMIN"
}

> {%
    client.global.set("role-id", response.body.id)
%}

###

GET localhost:8080/api/v1/admin/roles
Authorization: Bearer {{auth-token}}

###

GET localhost:8080/api/v1/admin/roles/id/{{role-id}}
Authorization: Bearer {{auth-token}}

###

GET localhost:8080/api/v1/admin/roles/{name}
Authorization: Bearer {{auth-token}}

###

PATCH localhost:8080/api/v1/admin/roles/{{role-id}}/users/{{us-uuid}}
Authorization: Bearer {{auth-token}}

###

DELETE localhost:8080/api/v1/admin/roles/{roleId}
Authorization: Bearer {{auth-token}}

##################ASSIGN ROLE TO USER

PUT localhost:8080/api/v1/admin/roles/4af4444f-630a-4d82-8827-4e268292d6d7/users/65c8953f-8206-47ff-84bc-9fbdb73b8f79
#Authorization: Bearer {{auth-token}}


################## COURSE

POST localhost:8080/api/v1/admin/courses
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "name": "Matura z matematyki Podstawowej"
}

> {%
    client.global.set("course-id", response.body.id)
%}

###

GET localhost:8080/api/v1/admin/courses
Authorization: Bearer {{auth-token}}
###

GET localhost:8080/api/v1/admin/courses/id/0b20d02b-42d9-4328-9254-e91421e356ac
Authorization: Bearer {{auth-token}}
###

GET localhost:8080/api/v1/admin/courses/Matura Matematyka Podstawowa
Authorization: Bearer {{auth-token}}
###


PATCH localhost:8080/api/v1/admin/courses/3fad1d6a-f04c-4d96-b220-aba44d0c2d05
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "name": "Mat - update2"
}

###


DELETE localhost:8080/api/v1/admin/courses/fb716900-35bb-4f5b-899f-ece06caad87e
Authorization: Bearer {{auth-token}}


###  OPINIONS

POST localhost:8080/api/v1/courses/1da12639-4ce8-4c06-9f25-381071c85de2/opinions
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{

  "description": "Kurs umożliwia mi śledzenie postępów i dostosowywanie tempa nauki."
}

> {%
   client.global.set("opinion-id", response.body.id)
%}


###
GET localhost:8080/api/v1/courses/1da12639-4ce8-4c06-9f25-381071c85de2/opinions

###

GET localhost:8080/api/v1/courses/{course-id}/opinions/{opinion-id}


###

DELETE localhost:8080/api/v1/admin/courses/0b20d02b-42d9-4328-9254-e91421e356ac/opinions/373f452b-fa11-4a40-832c-bbdcb9938af5
Authorization: Bearer {{auth-token}}

##################### USER - auth

POST localhost:8080/api/v1/auth/sign-up
Content-Type: application/json

{
  "firstName": "Nikola",
  "lastName": "Nowak",
  "email": "Nikola@gmail.com",
  "password": "Nikola123#",
  "repeatedPassword": "Nikola123#"
}
> {%
    client.global.set("us-uuid", response.body.id)
%}

###


POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "Nikola@gmail.com",
  "password":"Nikola123#"
}

> {% client.global.set("auth-token", response.body.token); %}

###

POST localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbGEzQGdtYWlsLmNvbSIsImlhdCI6MTcwNjE4MDkwMywiZXhwIjoxNzA2MTgyMzQzfQ.-H4PStOtwl0jZa14Qv1hzhggvH8opNw4-w87fIEEE88"
}

#################### USERS
GET localhost:8080/api/v1/admin/users
Authorization: Bearer {{auth-token}}

###

GET localhost:8080/api/v1/admin/users/{id}
Authorization: Bearer {{auth-token}}

###

GET localhost:8080/api/v1/admin/users/by-{email}
Authorization: Bearer {{auth-token}}

###

DELETE  localhost:8080/api/v1/admin/users/8b14d3dd-f48d-4cf0-8911-f0f2492ec816
Authorization: Bearer {{auth-token}}
###

GET http://localhost:8080/api/v1/admin/users
Authorization: Bearer {{auth-token}}

###



