################## ROLE

POST localhost:8080/api/v1/admin/roles
Content-Type: application/json

{
  "name": "USER"
}

> {%
    client.global.set("role-id", response.body.id)
%}

###

GET localhost:8080/api/v1/admin/roles

###

GET localhost:8080/api/v1/admin/roles/id/{{role-id}}

###

GET localhost:8080/api/v1/admin/roles/{name}

###

PATCH localhost:8080/api/v1/admin/roles/{{role-id}}/users/{{us-uuid}}

##################ASSIGN ROLE TO USER

PUT localhost:8080/api/v1/admin/roles/{{role-id}}/users/{{us-uuid}}



################## COURSE

POST localhost:8080/api/v1/admin/courses
Content-Type: application/json

{
  "name": "Matura Matematyka Podstawowa"
}

> {%
    client.global.set("course-id", response.body.id)
%}

###

GET localhost:8080/api/v1/admin/courses

###

GET localhost:8080/api/v1/admin/courses/{{course-id}}

###

DELETE localhost:8080/api/v1/admin/courses/{id}



###  OPINIONS

POST localhost:8080/api/v1/courses/{course-id}}/opinions
Content-Type: application/json

{
  "description": "jest ok"
}

> {%
   client.global.set("opinion-id", response.body.id)
%}


###
GET localhost:8080/api/v1/courses/{course-id}}/opinions

###

GET localhost:8080/api/v1/courses/{course-id}/opinions/{opinion-id}


###

DELETE localhost:8080/api/v1/courses/{course-id}/opinions/{opinion-id}

##################### USER - auth

POST localhost:8080/api/v1/auth/sign-up
Content-Type: application/json

{
  "firstName": "Bartek",
  "lastName": "Nowak",
  "email": "bartek@gmail.com",
  "password": "12345a1231912",
  "repeatedPassword": "12345a1231912"
}
> {%
    client.global.set("us-uuid", response.body.id)
%}

###

POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "ela3@gmail.com",
  "password": "12345a1231912"
}

###

POST localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbGEzQGdtYWlsLmNvbSIsImlhdCI6MTcwNjE4MDkwMywiZXhwIjoxNzA2MTgyMzQzfQ.-H4PStOtwl0jZa14Qv1hzhggvH8opNw4-w87fIEEE88"
}

#################### USERS



GET localhost:8080/api/v1/admin/users

###

GET localhost:8080/api/v1/admin/users/{id}

###

GET localhost:8080/api/v1/admin/users/by-{email}

###

DELETE  localhost:8080/api/v1/admin/users/{id}



###

GET http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbGEzQGdtYWlsLmNvbSIsImlhdCI6MTcwNjE4MzE1OSwiZXhwIjoxNzA2MTg0NTk5fQ.h_rComWMuV_YKliTJWfzw_XONcZtLhpdrGQnvhC75pY



